language: objective-c
git:
  depth: 10
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
before_install:
    - rvm use system
    - sudo gem install activesupport --version 4.2.5
    - sudo gem install cocoapods --no-prerelease --no-rdoc --no-ri --no-document
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
    - pod repo update >&/dev/null
    - cd TMLKit && pod install && pod update && cd ..
    - cd Demo && pod install && pod update && cd ..
    - cd TMLSandbox && pod install && pod update && cd ..
    - cd $TRAVIS_BUILD_DIR
env:
    global:
        - OTHER_XCTOOL_OPTS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
        - OTHER_XCODEBUILD_OPTS='-quiet CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
    matrix:
        - TRAVIS_XCODE_SDK='iphonesimulator8.4' TRAVIS_XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 5,OS=8.4'
        - TRAVIS_XCODE_SDK='iphonesimulator9.3' TRAVIS_XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 6s,OS=9.3'
        - TRAVIS_XCODE_SDK='iphonesimulator10.3' TRAVIS_XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
script: 
    - xcodebuild -workspace TMLKit/TMLKit.xcworkspace -configuration Release -scheme TMLKit -destination "$TRAVIS_XCODE_DESTINATION" $OTHER_XCODEBUILD_OPTS build-for-testing -sdk $TRAVIS_XCODE_SDK
    - xctool -workspace TMLKit/TMLKit.xcworkspace -configuration Release -scheme TMLKit -destination "$TRAVIS_XCODE_DESTINATION" $OTHER_XCTOOL_OPTS run-tests -test-sdk $TRAVIS_XCODE_SDK -parallelize
    - xcodebuild -workspace Demo/Demo.xcworkspace -configuration Release -scheme Demo -destination "$TRAVIS_XCODE_DESTINATION" $OTHER_XCODEBUILD_OPTS build -sdk $TRAVIS_XCODE_SDK
    - xcodebuild -workspace TMLSandbox/TMLSandbox.xcworkspace -configuration Release -scheme TMLSandbox -destination "$TRAVIS_XCODE_DESTINATION" $OTHER_XCODEBUILD_OPTS build -sdk $TRAVIS_XCODE_SDK
