source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target "TMLKit" do
	podspec :path => "../TMLKit.podspec"
end


target "TMLKitTests" do
	podspec :path => "../TMLKit.podspec"
end
