source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target "TMLKit" do
	podspec :path => "../Tml.podspec"
  pod 'SSZipArchive'
  pod 'NVHTarGzip'
end


target "TMLKitTests" do
	podspec :path => "../Tml.podspec"
  pod 'SSZipArchive'
  pod 'NVHTarGzip'
end
