source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target "Demo" do
	podspec :path => "../Tml.podspec"
    
    pod 'ViewDeck', '~> 2.2.11'
    pod 'SSZipArchive'
    pod 'NVHTarGzip'
end

target "DemoTests" do
	podspec :path => "../Tml.podspec"

end
